/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oce;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ChangePass extends javax.swing.JFrame {

    final String DB_URL = "jdbc:derby:DB;create=true;";  //Database URL
    final String USER = "app";
    final String PASS = "app";
    String User;
    String Password;
    HR hr;
    Admission A;
    Treasury T;

    public ChangePass() {
        initComponents();
    }

    public ChangePass(String P, String U,HR H) {
        initComponents();
        Password = P;
        User = U;
        hr=H;
    }
    public ChangePass(String P, String U,Admission a) {
        initComponents();
        Password = P;
        User = U;
        A=a;
    }
    public ChangePass(String P, String U,Treasury t) {
        initComponents();
        Password = P;
        User = U;
        T=t;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NP = new javax.swing.JPasswordField();
        CP = new javax.swing.JPasswordField();
        OP = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Old Password:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 20, -1, 22));

        jLabel2.setText("New Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 24));

        jLabel3.setText("Confirm Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 22));

        NP.setOpaque(false);
        getContentPane().add(NP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 130, -1));

        CP.setOpaque(false);
        getContentPane().add(CP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, -1));

        OP.setOpaque(false);
        OP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPActionPerformed(evt);
            }
        });
        getContentPane().add(OP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 130, -1));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        jButton3.setText("Done");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 70, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oce/Clouds.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        hr.Changing=false;
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (NP.getText().equals(CP.getText())) {
            if(NP.getText().length()>5)
            {
            if (OP.getText().equals(Password)) {
                String sql = "UPDATE USERS SET PASSWORD ='"+NP.getText()+"' WHERE USERNAME = '"+User+"'";
                Connection conn = null;
                Statement stmt = null;
                try {
                    //Register the JDBC driver
                    Class.forName("com.mysql.jdbc.Driver");

                    // Open a connection
                    conn = DriverManager.getConnection(DB_URL, USER, PASS);
                    System.out.println("Connected to database.");

                    //Execute query
                    stmt = conn.createStatement();
                    stmt.execute(sql);
                    if(hr!=null)
                    {
                        hr.SetPassword(NP.getText());
                        JOptionPane.showMessageDialog(this, "Password has been changed.");
                        hr.Changing=false;
                    }
                    else if(A!=null)
                        {
                            A.SetPassword(NP.getText());
                            JOptionPane.showMessageDialog(this, "Password has been changed.");
                            A.Changing=false;
                        }
                    else if(T!=null)
                    {
                        T.SetPassword(NP.getText());
                        JOptionPane.showMessageDialog(this, "Password has been changed.");
                        T.Changing=false;
                    }
                    this.dispose();
                } catch (Exception e) {
                  e.printStackTrace();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Incorrect old password.");
            }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "New password must be at least 6 characters.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "The 2 passwords do not match.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void OPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CP;
    private javax.swing.JPasswordField NP;
    private javax.swing.JPasswordField OP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
