/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oce;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class SignUp extends javax.swing.JFrame {

    final String DB_URL = "jdbc:derby:DB;create=true;";  //Database URL
    final String USER = "app";
    final String PASS = "app";

    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserName = new javax.swing.JTextField();
        Done = new javax.swing.JButton();
        Number = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Cpassword = new javax.swing.JPasswordField();
        Password = new javax.swing.JPasswordField();
        Name = new javax.swing.JTextField();
        DOB = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Cancel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        UserName.setOpaque(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Done.setText("Done");
        Done.setOpaque(false);
        Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneActionPerformed(evt);
            }
        });
        getContentPane().add(Done, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 100, -1));

        Number.setOpaque(false);
        getContentPane().add(Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 150, -1));

        jLabel1.setText("Username:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 20));

        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 110, 20));

        jLabel3.setText("Confirm Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, 20));

        jLabel4.setText("Email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 110, 20));

        jLabel5.setText("Date of birth:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 110, 20));

        jLabel6.setText("Phone Number:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 110, 20));

        jLabel7.setText("Name:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 20));

        Username.setOpaque(false);
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 150, -1));

        Cpassword.setOpaque(false);
        getContentPane().add(Cpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 150, -1));

        Password.setOpaque(false);
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, -1));

        Name.setOpaque(false);
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 150, -1));

        DOB.setOpaque(false);
        getContentPane().add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 150, -1));

        Email.setOpaque(false);
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 150, -1));

        Cancel.setText("Cancel");
        Cancel.setOpaque(false);
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 90, -1));

        jLabel9.setText(" Welcome!");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oce/Clouds.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        Login L = new Login();
        L.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneActionPerformed
        if (Username.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter a username.");
            return;
        }
        if (Password.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter a password.");
            return;
        }
        if (Cpassword.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please confirm the password.");
            return;
        }
        if (Name.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter your name.");
            return;
        }
        if (DOB.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter your date of birth.");
            return;
        }
        if (Email.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter your email.");
            return;
        }
        if (Number.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter your phone number.");
            return;
        }
        if (!(Password.getText().equals(Cpassword.getText()))) {
            JOptionPane.showMessageDialog(this, "The 2 passwords do not match.");
            Password.setText("");
            Cpassword.setText("");
            return;
        }
        if (Password.getText().length() < 6) {
            JOptionPane.showMessageDialog(this, "The password should contain at least 6 characters.");
            Password.setText("");
            Cpassword.setText("");
            return;
        }
        EmailValidator E = new EmailValidator();
        if (!E.validate(Email.getText())) {
            JOptionPane.showMessageDialog(this, "Invalid Email ID.");
            return;
        }
        Check();
    }//GEN-LAST:event_DoneActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void Check()
    {
        String sql="SELECT * FROM USERS";
        Connection conn = null;
        Statement stmt = null;
        try {
            //Register the JDBC driver
            Class.forName("com.mysql.jdbc.Driver");

            // Open a connection
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            System.out.println("Connected to database.");

            //Execute query
            stmt = conn.createStatement();

            ResultSet rs=stmt.executeQuery(sql);
            while(rs.next())
            {
                if(rs.getString("USERNAME").toLowerCase().equals(Username.getText().toLowerCase()))
                {
                    JOptionPane.showMessageDialog(this, "Username already is use.");
                    return;
                }
            }
            Save();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
    }
    
    public void Save() {
        String sql = "INSERT INTO USERS (USERNAME ,PASSWORD,DEPARTMENT, PHONE ,EMAIL,NAME ,BIRTH) VALUES ('"+Username.getText()+"','"+Password.getText()+"',' ','"+Number.getText()+"','"+Email.getText()+"','"+Name.getText()+"','"+DOB.getText()+"')";
        Connection conn = null;
        Statement stmt = null;
        try {
            //Register the JDBC driver
            Class.forName("com.mysql.jdbc.Driver");

            // Open a connection
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            System.out.println("Connected to database.");

            //Execute query
            stmt = conn.createStatement();

            stmt.execute(sql);
            JOptionPane.showMessageDialog(this, "You have been registered successfully, you will not be able to log in until an HR employee has confirmed your account!");
            Login L = new Login();
            L.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            sql = "CREATE TABLE USERS (USERNAME varchar(255),PASSWORD varchar(255),DEPARTMENT varchar(255), PHONE varchar(255),EMAIL varchar(255),NAME varchar(255),BIRTH varchar(255),POSITION varchar(255),SALARY DOUBLE, RECORDS varchar(255),PRIMARY KEY (USERNAME))";
            try {
                e.printStackTrace();
                stmt.execute(sql);
                System.out.println("Table created");
                sql = "INSERT INTO USERS (USERNAME ,PASSWORD,DEPARTMENT, PHONE ,EMAIL,NAME ,BIRTH) VALUES ('"+Username.getText()+"','"+Password.getText()+"',' ','"+Number.getText()+"','"+Email.getText()+"','"+Name.getText()+"','"+DOB.getText()+"')";
                stmt.execute(sql);
                sql = "INSERT INTO USERS (USERNAME ,PASSWORD,DEPARTMENT, PHONE ,EMAIL,NAME ,BIRTH,SALARY,RECORDS,POSITION) VALUES ('Elio1','123456','HR','70336193','elio.bouhabib@lau.edu','Elio Bou Habib','27/07/1992',1000,'Default account.\n','Manager')";
                stmt.execute(sql);
                JOptionPane.showMessageDialog(this, "You have been registered successfully, you will not be able to log in until an HR employee has confirmed your account!");
                Login L = new Login();
                L.setVisible(true);
                this.dispose();
                
            } catch (Exception f) {
                f.printStackTrace();
            }
            finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JPasswordField Cpassword;
    private javax.swing.JTextField DOB;
    private javax.swing.JButton Done;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Number;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField UserName;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
